### ISSUE TITLE
Hitting error: Cannot find module 'babel-runtime/core-js/get-iterator'

### ISSUE THREAD

**Issue by josoroma-zz** [FormidableLabs/aws-lambda-serverless-reference#28] opened 2019-08-07 18:28 UTC
## API Gateway Log:

```
Wed Aug 07 18:14:14 UTC 2019 : Lambda execution failed with status 200 due to customer function error: Cannot find module 'babel-runtime/core-js/get-iterator'. Lambda request id: c15fe0ce-ac90-4c23-b156-ca78e1b42fc7
Wed Aug 07 18:14:14 UTC 2019 : Method completed with status: 502
```

**Comment by ryan-roemer** [comment] 2019-08-07 18:53
Is this a reproduction off _this_ project or your custom application code?

Seems like it can't possibly be this project as `babel-runtime` is not a direct or transitive dependency of anything here and is nowhere in https://github.com/FormidableLabs/aws-lambda-serverless-reference/blob/master/yarn.lock

**Comment by ryan-roemer** [comment] 2019-12-03 04:53
Closing due to lack of reproduction against this project.

**Closed as completed by ryan-roemer** 2019-12-03 04:53 UTC
Labels: unverified
